### PR TITLE
Brazilia Portuguese translation

### PR DESCRIPTION
**Pull request by carlisson**
I have translated to Brazilian Portuguese, based on project instructions.

Cordial,

### CODE REVIEW

**Comment by Andre-LA** [comment]
Hello, I did an review, I have some notes, but the translation is correct!

* "Self-hosting" is translated as "embutido", but some sources (including Wikipedia) translates it to "auto-hospedagem".
* "free and open-source software" is translated as "software gratuito e de código aberto"; maybe it should be changed to "livre" (as in "software livre").

And that's it, the only one I'm undecided about is the "self-hosting" one, but the "free" one isn't incorrect, but using "livre" might be more aligned with what the authors want to communicate.

**Comment by carlisson** [comment]
Ok, Thank you for the corrections. Really, self-hosting is better translated as auto-hospedado.

**Comment by colinkiama** [comment]
Thank you!

**Comment by colinkiama** [comment]
By the way, do you want your details added to [humans.txt](static/humans.txt)?

**Comment by carlisson** [comment]
Yes. How can we do that? Another pull request? Sorry, it's the first time I have contributed to any project using git

**Comment by colinkiama** [comment]
Yes

**Pull request merged**
